travis:
  secure:
    BINSTAR_TOKEN: EE4pzZysKEyebDmJzpwZvU91WCIfytZ6NWgFse2RbhCEsvkoG8fv+XYzcEcWptCGoBDqAuF3QSN6NRiM7juG03X9XT5NoA9/ln20uMe7k+UtFKXIsPdrPrnpsdAD9N3V5Sbsxptltl9AG1hP26tRiCwf7a1Xrs33wvZnPqMOSL6zxFH5eakqD6gKZ37rdOCJ6C50KmDl/7BvdAOq83topiynonHVAXhCHY5Yzh4TkVRVc734Vaifa7q9em2hmmB657T87Rejk2qE8DmVl9XqqOCsxr+L1iIvaPaMMqW1ZDA9RXugJkKENYmIar00XiVRUXopyRvQeSzI4oKl3XrrrPCuQ2rr/0zbUvST0xLUeCLgA9274/PaCNyvAIqojdl9u4eZU59ILOvmSU1V+SkUL9vg99OS8ea1ZrODtnf4RbnzjD24Tm2X1zdMonuFWp73Uu4PHsPJAFUAAzdLoYS7E3UhJA7EfA6Oty5xH6b3sS9wkahdA8ikXzYA0z1i6E9tXyLhnca8r5PH3/wx7+i9QNY+MnVqjFDg1DLv37uPFCl4xCYbxo9TA8cB2MTt00sMJM0wrw0YpCV6tvpwKWt2O32xmy9kBjua7U+h+S5qLyA6e/povOR1sK8hJ3UHFtNXnAEqBXYNvU1u7eNjBrTlqGbBWXixoo31jqTTtcxlLfI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
